packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

locals {
  timestamp       = regex_replace(timestamp(), "[- TZ:]", "")
  region          = "us-east-1"
  
  tags = {
    Name          = "nomad-tf-mws_${formatdate("YYYY-MM-DD", timestamp())}"
    OS_Version    = "Ubuntu 22.04 LTS"
    Created_Name  = "mikael.sikora"
    HashiStack    = "Consul 1.7.8, Nomad 1.10.2, Vault 1.19.5"
    Created_Date  = formatdate("YYYY-MM-DD", timestamp())
    Base_AMI_ID   = "${data.amazon-ami.autogenerated_1.id}"
  }
}

data "amazon-ami" "autogenerated_1" {
  filters = {
    architecture                       = "x86_64"
    "block-device-mapping.volume-type" = "gp2"
    name                               = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
    root-device-type                   = "ebs"
    virtualization-type                = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "us-east-1"
}

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "HashiStack ${local.timestamp}"
  instance_type = "t3a.xlarge"
  region        = local.region
  source_ami    = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username  = "ubuntu"
  tags          = local.tags
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sudo mkdir /ops", "sudo chmod 777 /ops"]
  }

  provisioner "file" {
    destination = "/ops"
    source      = "../shared"
  }

  provisioner "file" {
    destination = "/ops"
    source      = "../examples"
  }

  provisioner "shell" {
    environment_vars = ["INSTALL_NVIDIA_DOCKER=true"]
    script           = "../shared/scripts/setup.sh"
  }
}
